### ISSUE TITLE
is_alive() and all_loaded() service status enquiries seems broken

### ISSUE THREAD

**Issue by AIIX** [OpenVoiceOS/ovos-core#101]
Tried the following on latest ovos-core dev branch git install:

For is_alive():

Messagebus Service:
Client Sending -> "mycroft.messagebus.is_alive" / " "mycroft.bus.is_alive" : Expected Response -> "mycroft.messagebus.is_alive.response" /  "mycroft.bus.is_alive.response" : Got Response: None

Skills Service:
Client Sending -> "mycroft.skills.is_alive" : Expected Response -> "mycroft.skills.is_alive.response" : Expected Single Response, Got Multiple Responses one after the other for a single request, received in following order: 
- mycroft.skills.is_alive.response {"status":true}
- mycroft.skills.is_alive.response {"status":false}

For all_loaded():

Client Sends: "mycroft.skills.all_loaded" : Expected Response -> "mycroft.skills.all_loaded.response" : Expected Single Response, Got Multiple Responses one after the other for a single request, received in the following order:
- mycroft.skills.all_loaded.response {"status":true}
- mycroft.skills.all_loaded.response {"status":false}

**Comment by NeonDaniel** [comment]
Is it possible the skills or messagebus service was running multiple instances?

**Comment by JarbasAl** [comment]
@AIIX can this be closed? in the chat we reached the conclusion it was the old home screen skill also initing a skillservice internally, or am i confusing things?
