### ISSUE TITLE
Install confusion

### ISSUE THREAD

**Issue by Steven11q** [OpenVoiceOS/ovos-core#239]
Ive been trying to follow the docs and install procedure but its a bit of a mess. Could someone please explain how I install and run ovos-core? The documentation makes it sound like running the pip install will create a folder but I see no such thing?

**Comment by builderjer** [comment]
It should install scripts into `~/.local/bin`. They will be `mycroft-****`

**Comment by builderjer** [comment]
Ovos does not quite work that way. You are able to start each service separately depending on your needs. I think one of the developers could guide you a bit more. But as I said in the chats, the pre-built images for the pi4 are the easiest way to get going. Every other platform is not fully supported yet and takes fiddling to get it all up and running. You can find the images at OpenVoiceOS.com

**Comment by Steven11q** [comment]
I see, Thanks for the help! If you know where I could find some more info on properly running core it would be greatly appreciated but its nice to no longer be banging my head against a wall lol

**Comment by NeonDaniel** [comment]
You might check out the Docker implemented modules in [NeonCore](https://github.com/NeonGeckoCom/NeonCore). A little easier to get up and running if you just want to try things or work on developing a skill
