### ISSUE TITLE
fix docker build

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-core#267]
rapidfuzz is failing to install for several releases now

**Comment by maxemoose** [comment]
Hey Jarbas. Was just messing around trying to get this working and discovered the last working version of rapidfuzz that will install. I changed line 17 of the Dockerfile to this:

`RUN pip3 install rapidfuzz==2.11.1`

Then the image would build. The build process will fail if using version 2.12.0 or greater.

**Comment by JarbasAl** [comment]
closing this one, first class docker support now lives in https://github.com/OpenVoiceOS/ovos-docker
