### ISSUE TITLE
Select a new STT engine for unit tests

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-core#289]
Tests are failing because the Selene dependency appears to be removed from PyPI. Can we pick a different engine for unit tests and open a separate PR to implement that change?

_Originally posted by @NeonDaniel in https://github.com/OpenVoiceOS/ovos-core/issues/288#issuecomment-1449192082_

**Comment by mikejgray** [comment]
@NeonDaniel Good to close?

**Comment by NeonDaniel** [comment]
No loner relevant
