### ISSUE TITLE
Add padatious to extra-skills.txt

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-core#299]
When running only the skills service, `minimal.txt` and `extra-skills.txt` are required but it still miss the `padatious` library which returns an error.

```
2023-03-27 22:14:16.376 - skills - mycroft.skills.intent_services.padatious_service:__init__:150 - ERROR - Padatious not installed. Falling back to pure regex alternative
```

**Comment by JarbasAl** [comment]
It is intended, it uses padacioso if padatious is missing

the aim was to make padatious optional, both due to depending on system libs (fann2) and license concerns (flagged by our automations, missed by mycroft)

there is skills_lgpl extras which includes padatious

**Comment by goldyfruit** [comment]
Ooohhh, then maybe replace the `ERROR` by a `WARNING` because my first intent was to install `padatious`. xD

**Comment by JarbasAl** [comment]
https://github.com/OpenVoiceOS/ovos-plugin-manager/pull/47 will solve this, this was temporary and padacioso needs more testing, so installing padatious is good, but we get to claim its optional which is what matters ;)

**Comment by goldyfruit** [comment]
Perfect, thanks!
