### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-core#30]
ovos-core needs some unit tests; here's a quick draft of what I think we need:

- [x] Implement GH Action for Coverage
- [x] Implement GH Action to run unit tests
- [ ] Curate Mycroft tests and remove/rework any that don't run under ovos-core
- [ ] Add unit tests per Coverage

**Comment by ChanceNCounter** [comment]
The repo may or may not already be set up at Codecov. The org is.

**Comment by JarbasAl** [comment]
closing in favor of https://github.com/OpenVoiceOS/ovos-core/issues/415 to track this
