### ISSUE TITLE
Enable GitHub Discussion.

### ISSUE THREAD

**Issue by rokejulianlockhart** [OpenVoiceOS/ovos-core#333]
My rationale is available at https://github.com/8go/matrix-commander/issues/68#issue-1237645245.

More specifically, I don't see any forum for this project, and https://app.element.io/#/room/#openvoiceos:matrix.org isn't a replacement for one. Would you consider enabling Discussions so that I can ask questions without creating new issues for them? https://github.com/OpenVoiceOS/ovos-core#links just links to https://community.mycroft.ai/.

**Comment by rokejulianlockhart** [comment]
> ~~More specifically, I don't see any forum for this project, and https://app.element.io/#/room/#openvoiceos:matrix.org isn't a replacement for one. Would you consider enabling Discussions so that I can ask questions without creating new issues for them?~~

https://github.com/OpenVoiceOS/ovos-core#links

**Comment by JarbasAl** [comment]
they are enabled at org level

https://github.com/orgs/OpenVoiceOS/discussions
