### ISSUE TITLE
0.0.7 Installation Errors

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-core#341]
[A but in pyyaml](https://github.com/yaml/pyyaml/issues/724) means that the current stable `ovos-core` will fail during installation. There are two workarounds:

1. Install pyyaml 5.4 manually first:
```
pip install  "cython<3.0.0"
pip install --no-build-isolation pyyaml~=5.4
pip install ovos-core[skills]  # or `pip install ovos-core[skills_lgpl]`
```

2. Skip the `skills` (or `skills_lgpl` extras) and install them manually:
```
pip install ovos-core
pip install adapt-parser~=0.5 padacioso~=0.1 ovos-lingua-franca>=0.4.7 ovos-phal-connectivity-events~=0.0.1
# If using Padatious (skills_lgpl extras), also:
pip install padatious~=0.4.8 fann2==1.0.7
```

**Comment by JarbasAl** [comment]
master is now on 0.0.8, closing
