### ISSUE TITLE
[BUG] Classic Mycroft skill inits are not calling self.initialize()

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-core#343]
Per findings here:
https://github.com/OpenVoiceOS/skill-ovos-wolfie/pull/14

In at least one case, and possibly in the wikipedia skill too, a skill with a `create_skill()` function and a Skill `self.initialize()` method is not calling the `self.initialize()` method.

```bash
ovos@mark1-dev:~ $ pip list | grep ovos-core
ovos-core                            0.0.8a27
```

Not sure how far back this goes, but this is the version on the Mark 1 where I found the issue. Running RaspOvos image for Mark 1.

**Comment by JarbasAl** [comment]
i think this has been fixed in the meantime

**Comment by JarbasAl** [comment]
can't replicate, closing. re-open if theres still an issue
