### ISSUE TITLE
Can't install ovos-core and ovos-bus-client

### ISSUE THREAD

**Issue by WhyNine** [OpenVoiceOS/ovos-core#344]
ovos-core has the requirement:
ovos_bus_client<0.0.6a1, >=0.0.5

However ovos-bus-client is at version 0.0.6a4 (https://github.com/OpenVoiceOS/ovos-bus-client/blob/dev/CHANGELOG.md).

It appears impossible to install both at the same time!

**Comment by JarbasAl** [comment]
this is because of #342 , it is avoiding a bug introduced in 0.0.6a2, fixed in  https://github.com/OpenVoiceOS/ovos-bus-client/pull/46

the version can now be set to >=0.0.6a4 in this repo, perhaps update #339 to include the bus

**Comment by JarbasAl** [comment]
this no longer applies
