### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by ChanceNCounter** [OpenVoiceOS/ovos-core#35]
Somebody should take #4 and continue the job, adding instructions for starting OVOS-Core after a pip or a git install. I am not familiar enough with the changes to finish it myself, and we've gotten questions ("I installed it now what?")

Generally speaking, the practice of making changes and then putting up a TODO for somebody to document them needs to stop. It's hard enough to document your own code after a break. Trying to document somebody else's code is a nightmare. If somebody is less than confident in their English, write your docs and then ping me or Daniel to clean them up. </rant>

**Comment by mikejgray** [comment]
@ChanceNCounter Is this still valid? Quite old, not sure if it's been addressed (the context is old and unclear to me)
