### ISSUE TITLE
skill migration guide

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-core#382]
# OVOS Skill Replacements

also see  [Adopt a project](https://github.com/orgs/OpenVoiceOS/discussions/169) discussion and https://github.com/OVOSHatchery

## Old Mycroft

migration guide

- [x] https://github.com/MycroftAI/skill-ip -> https://github.com/OpenVoiceOS/skill-ip
- [x] https://github.com/MycroftAI/skill-date-time -> https://github.com/OpenVoiceOS/skill-ovos-date-time
- [x] https://github.com/MycroftAI/skill-personal -> https://github.com/OpenVoiceOS/skill-ovos-personal
- [x] https://github.com/MycroftAI/skill-joke -> https://github.com/OpenVoiceOS/skill-ovos-icanhazdadjokes
- [x] https://github.com/MycroftAI/skill-wiki -> https://github.com/OpenVoiceOS/skill-ovos-wikipedia
- [x] https://github.com/MycroftAI/skill-naptime -> https://github.com/OpenVoiceOS/skill-ovos-naptime
- [x] https://github.com/MycroftAI/skill-spelling ->  https://github.com/OpenVoiceOS/skill-spelling
- [x] https://github.com/MycroftAI/skill-hello-world -> https://github.com/OpenVoiceOS/skill-ovos-hello-world
- [ ] https://github.com/MycroftAI/skill-version-checker -> TODO (?)
- [ ] https://github.com/MycroftAI/skill-singing -> https://github.com/OpenVoiceOS/ovos-skill-easter-eggs/issues/27
- [x] https://github.com/MycroftAI/skill-wifi-connect -> NOT WANTED/DEPRECATED , handled natively via PHAL plugins
- [x] https://github.com/MycroftAI/mycroft-mark-1 -> https://github.com/JarbasSkills/skill-enclosure-ctrl
- [x] https://github.com/MycroftAI/skill-installer -> NOT WANTED/DEPRECATED
- [x] https://github.com/MycroftAI/skill-configuration -> NOT WANTED/DEPRECATED
- [x] https://github.com/MycroftAI/skill-pairing -> NOT WANTED/DEPRECATED https://github.com/OpenVoiceOS/skill-ovos-setup
- [x] https://github.com/MycroftAI/skill-support -> NOT WANTED/DEPRECATED
- [x] https://github.com/MycroftAI/skill-stock  -> NOT WANTED/DEPRECATED https://github.com/NeonGeckoCom/skill-stock
- [ ] https://github.com/MycroftAI/skill-pandora -> REGION LOCKED == BAD , someone that isn't OVOS should maintain this one
- [x] https://github.com/MycroftAI/skill-stop -> https://github.com/OpenVoiceOS/skill-ovos-stop  -> NOT WANTED/DEPRECATED in **0.0.8** , native part of OVOS-core
- [x] https://github.com/MycroftAI/skill-volume ->  https://github.com/OpenVoiceOS/skill-ovos-volume
- [x] https://github.com/MycroftAI/skill-npr-news ->  https://github.com/OpenVoiceOS/skill-ovos-news
- [x] https://github.com/MycroftAI/skill-alarm ->  https://github.com/OpenVoiceOS/skill-alerts
- [x] https://github.com/MycroftAI/skill-reminder ->  https://github.com/OpenVoiceOS/skill-alerts
- [x] https://github.com/MycroftAI/mycroft-timer ->  https://github.com/OpenVoiceOS/skill-alerts
- [x] https://github.com/MycroftAI/skill-weather ->  https://github.com/OpenVoiceOS/skill-ovos-weather
- [x] https://github.com/MycroftAI/skill-speak -> https://github.com/OpenVoiceOS/skill-ovos-parrot
- [x] https://github.com/MycroftAI/fallback-duckduckgo ->  https://github.com/OpenVoiceOS/skill-ovos-ddg
- [x] https://github.com/MycroftAI/fallback-unknown -> https://github.com/OpenVoiceOS/skill-ovos-fallback-unknown
- [x] https://github.com/MycroftAI/fallback-wolfram-alpha -> https://github.com/OpenVoiceOS/skill-ovos-wolfie
- [x] https://github.com/MycroftAI/skill-homeassistant ->  https://github.com/OpenVoiceOS/ovos-PHAL-plugin-homeassistant + https://github.com/mikejgray/neon-homeassistant-skill
- [x] https://github.com/MycroftAI/skill-playback-control ->  NOT WANTED/DEPRECATED , native part of OVOS via [OCP](https://github.com/OpenVoiceOS/ovos-ocp-audio-plugin)
- [x] https://github.com/MycroftAI/skill-query -> NOT WANTED/DEPRECATED , native part of OVOS-core
- [x] https://github.com/MycroftAI/skill-audio-record  -> https://github.com/NeonGeckoCom/skill-audio-recording -> https://github.com/OpenVoiceOS/skill-ovos-audio-recording

GUI skills
- [x] https://github.com/MycroftAI/skill-homescreen -> https://github.com/OpenVoiceOS/skill-ovos-homescreen or https://github.com/OpenVoiceOS/skill-homescreen-lite
- [x] https://github.com/MycroftAI/skill-camera -> https://github.com/OpenVoiceOS/skill-ovos-qml-camera
- [x] https://github.com/MycroftAI/skill-mycroft-radio -> several skill options for OCP https://github.com/OpenVoiceOS/skill-ovos-tunein
- [x] https://github.com/MycroftAI/skill-music-demo -> several skill options for OCP 

## Community

to be updated / forked / rewritten officially by OVOS

- [x] https://github.com/zelmon64/skill-finished-booting -> https://github.com/NeonGeckoCom/skill-core_ready -> https://github.com/OpenVoiceOS/skill-ovos-boot-finished
- [x] https://github.com/NeonGeckoCom/skill-alerts -> https://github.com/OpenVoiceOS/skill-alerts
- [x] https://github.com/luke5sky/discontinued-speedtest-skill -> https://github.com/NeonGeckoCom/skill-speed_test -> https://github.com/OpenVoiceOS/ovos-skill-speedtest
- [ ] https://github.com/andlo/auto-volume-skill ->  https://github.com/OpenVoiceOS/ovos-PHAL-plugin-alsa/issues/25
- [x] https://github.com/lhannon/decide-skill -> https://github.com/OpenVoiceOS/skill-ovos-randomness
- [x] https://github.com/Dragoncraft89/dice-skill -> https://github.com/OpenVoiceOS/skill-ovos-randomness
- [x] https://github.com/pcwii/skill-pick-number -> https://github.com/OpenVoiceOS/skill-ovos-randomness
- [x] https://github.com/wligtenberg/coin-flip-skill -> https://github.com/OpenVoiceOS/skill-ovos-randomness
- [x] https://github.com/Arc676/Crystal-Ball-Mycroft-Skill -> https://github.com/OpenVoiceOS/skill-ovos-randomness
- [ ] https://github.com/andlo/iss-tracker-skill -> https://github.com/JarbasSkills/skill-iss-location
- [x] https://github.com/forslund/spotify-skill -> https://github.com/OpenVoiceOS/skill-ovos-spotify
- [x] https://github.com/builderjer/moviemaster  -> @builderjer  https://github.com/OpenVoiceOS/ovos-skill-moviemaster
- [ ] https://github.com/LinusSkucas/email-skill -> TODO REPLACEMENT - email PHAL plugin
- [ ] https://github.com/JarbasSkills/skill-email-commands  -> TODO REPLACEMENT - HiveMind bridge
- [x] https://github.com/forslund/fallback-aiml -> use via persona https://github.com/OpenVoiceOS/ovos-solver-plugin-aiml

**Comment by mikejgray** [comment]
https://github.com/mikejgray/skill-randomness Candidate code to replace the 5 skills in the `Community` section above
