### ISSUE TITLE
[BUG] all fallback answer

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-core#389]
**Describe the bug**
If you install _skill-ovos-fallback-chatgpt_ along another fallback skill, both fallback will answer

**To Reproduce**
1. Install skill-ovos-fallback-unknown
2. Install skill-ovos-fallback-chatgpt
3. Ask something weird (it happen a lot when not using English)
4. Both fallback skills answer

**Expected behavior**
The first fallback that answer should close the dialogue.

**Additional context**
Chatgpt takes a long time to answer, this causes a time out and makes fallback service go to next skill, but the fallback that timed out is not stopped

**Comment by mikejgray** [comment]
@JarbasAl Fixed? Can we close?

**Comment by JarbasAl** [comment]
not fixed, a older chatgpt skill exposes the issue

if a fallback takes too long to answer core goes to the next one assuming it crashes, so very slow fallbacks will still trigger, after another one has been selected

its not all fallbacks answering, its a fallback timing out and still executing at a later point
