### ISSUE TITLE
Log level set within system conf not being honoured

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/ovos-core#40]
mycroft.conf within etc states;

 "log_level": "INFO"

However DEBUG messages are shown in all the logs

**Comment by NeonDaniel** [comment]
In `mycroft.__init__()`, it looks like a TODO that didn't have "TODO" in it:
```python
LOG.init()  # read log level from config
```

**Comment by emphasize** [comment]
i guess we should close this. The was some work around logs init / config / etc. that i doubt this 2 year old issue is still ongoing.
At least i have no way to reproduce.

**Comment by j1nx** [comment]
Yeah, this has solved a long time ago indeed. Closing.

**Comment by voronaivan93** [comment]
Hello . No Internet 😭😔.

сб, 20 янв. 2024 г., 17:56 Peter Steenbergen ***@***.***>:
