### ISSUE TITLE
port -  resource file handling utils

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-core#41]
potential commit of interest in `mark2/qa` branch - https://github.com/MycroftAI/mycroft-core/commit/b9f814a03cb482a1b1c27b580be477b3463927de

**Comment by NeonDaniel** [comment]
Looks interesting; `translator` raises some questions for me since Neon defines a translator to perform language translation, whereas the one defined here seems to just resolve the correct resource file

**Comment by JarbasAl** [comment]
closed by #130 , but also needs #135 bugfix to be merged soon
