### ISSUE TITLE
port - mk2 gui refactor

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-core#42]
potential commits of interest in `mark2/qa` branch

 move GUI specific code out from the base enclosure class and refactor  -   https://github.com/MycroftAI/mycroft-core/commit/235bd0c9ef09828a79fc1b90a4c04ed6aa0a1262
 
 Initial implementation of an IdleDisplaySkill -  https://github.com/MycroftAI/mycroft-core/commit/68f870dfe54ae6aea00fa6807bad514d1aae20b0
 
 new SkillGUI helper method to replace the page - https://github.com/MycroftAI/mycroft-core/commit/3c594fba1e3d183f876ce7870cf3d98ef528ff2d

**Comment by AIIX** [comment]
Done: https://github.com/OpenVoiceOS/ovos-core/pull/64
ToDo: https://github.com/MycroftAI/mycroft-core/commit/3c594fba1e3d183f876ce7870cf3d98ef528ff2d
