### ISSUE TITLE
Missing backwards-compat. imports

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-core#433]
`mycroft.skills.intent_services.adapt_service.AdaptIntent` is not backwards-compatible
https://github.com/NeonGeckoCom/NeonCore/pull/641#issuecomment-2035787446

`mycroft.util.record` is missing
https://github.com/NeonGeckoCom/NeonCore/pull/641#issuecomment-2035788147

**Comment by JarbasAl** [comment]
related to https://github.com/OpenVoiceOS/ovos-core/issues/433
