### ISSUE TITLE
Stable Dependencies for 0.0.8 Release

### ISSUE THREAD

**Issue by NeonDaniel** [OpenVoiceOS/ovos-core#488]
This is a list of open issues or PRs that are necessary for stable releases of these ovos-core dependencies. Note that these dependencies may themselves have alpha dependencies that need a stable release as well.

## [ovos-config](https://github.com/OpenVoiceOS/ovos-config)
- https://github.com/OpenVoiceOS/ovos-config/issues/118
- https://github.com/OpenVoiceOS/ovos-config/issues/125
- https://github.com/OpenVoiceOS/ovos-config/issues/108

## [ovos-workshop](https://github.com/OpenVoiceOS/OVOS-workshop)
- https://github.com/OpenVoiceOS/OVOS-workshop/pull/206

## [ovos-classifiers](https://github.com/OpenVoiceOS/ovos-classifiers)
- https://github.com/OpenVoiceOS/ovos-classifiers/pull/24

## [ovos-PHAL](https://github.com/OpenVoiceOS/ovos-PHAL)
- https://github.com/OpenVoiceOS/ovos-PHAL/pull/32

## [ovos-audio](https://github.com/OpenVoiceOS/ovos-audio)
- https://github.com/OpenVoiceOS/ovos-audio/issues/68
- https://github.com/OpenVoiceOS/ovos-audio/issues/52
- https://github.com/OpenVoiceOS/ovos-audio/issues/47

## [ovos-listener](https://github.com/OpenVoiceOS/ovos-listener/issues)
- Triage issues and close most/all as "wontfix" as the project is deprecated in favor of ovos-dinkum-listener
- https://github.com/OpenVoiceOS/ovos-listener/issues/22
- https://github.com/OpenVoiceOS/ovos-listener/issues/17

## [ovos-dinkum-listener](https://github.com/OpenVoiceOS/ovos-dinkum-listener)
- [x] https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/107
- [x] https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/110 / https://github.com/OpenVoiceOS/ovos-dinkum-listener/pull/114
- [x] https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/98
- [x]  https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/88 / https://github.com/OpenVoiceOS/ovos-dinkum-listener/pull/115

## [ovos-gui](https://github.com/openvoiceos/ovos-gui)
- dependency updates and stable release, no open issues

## [ovos-backend-client](https://github.com/openvoiceos/ovos-backend-client)
- dependency updates and stable release
- https://github.com/OpenVoiceOS/ovos-backend-client/issues/59 / https://github.com/OpenVoiceOS/ovos-backend-client/pull/61

**Comment by JarbasAl** [comment]
added support for utils 0.0.38 back in OCP, it also needs a stable release, but @mikejgray reported a bug with playlists there that needs to be fixed first

**Comment by JarbasAl** [comment]
dinkum-listener
- [ ] https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/107
- [ ] https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/110 + https://github.com/OpenVoiceOS/ovos-dinkum-listener/pull/114
- [ ] https://github.com/OpenVoiceOS/ovos-dinkum-listener/issues/98

**Comment by JarbasAl** [comment]
started running the automations across repos
- https://github.com/OpenVoiceOS/ovos-utils/pull/264

**Comment by JarbasAl** [comment]
phal plugins
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-dotstar/releases/tag/V0.0.1
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-ipgeo/releases/tag/0.0.2
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-system/releases/tag/0.0.4
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-connectivity-events/releases/tag/0.0.3
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-network-manager/releases/tag/1.1.0
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-oauth/releases/tag/0.0.2
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-alsa/releases/tag/0.0.3
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-wifi-setup/releases/tag/1.1.1
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-mk1 - **MISSING AUTOMATIONS**
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-mk2-v6-fan-control - **MISSING AUTOMATIONS**
- https://github.com/OpenVoiceOS/ovos-PHAL-plugin-hotkeys - **MISSING AUTOMATIONS**

**Comment by JarbasAl** [comment]
closing this, tracking final steps around semver here https://github.com/OpenVoiceOS/ovos-core/pull/538
