### ISSUE TITLE
skill-laugh shouldn't be part of skills-extra

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-core#633]
skill-laugh is a fun novelty, but including it in skills-extra makes it difficult to remove from your pyproject.toml or requirements.txt if you include ovos-core[skills-extra].

**Comment by JarbasAl** [comment]
Skills extra is meant to include all official skills that aren't installed by default, and to ensure the tests pass with that combination, that list will only grow. If you want any control whatsoever over the installed skills, that's an extra you should skip

**Comment by mikejgray** [comment]
That should probably be better documented

**Comment by JarbasAl** [comment]
maybe renaming it to all-skills would make it more clear?
