### ISSUE TITLE
tflite not available in py3.10

### ISSUE THREAD

**Issue by NeonJarbas** [OpenVoiceOS/ovos-core#76]
precise lite plugin will fail to install in py3.10, build_all workflow will fail in PRs until tflite_runtime becomes available

**Comment by NeonDaniel** [comment]
Is there an issue for this in the source repo of that package yet?

**Comment by JarbasAl** [comment]
closing as out of scope, default requirements dont need this anymore

fixed by providing wheels https://github.com/OpenVoiceOS/ovos-binary-shop/releases and https://whl.smartgic.io/
