### ISSUE TITLE
Failure when no fallback stt set

### ISSUE THREAD

**Issue by builderjer** [OpenVoiceOS/ovos-core#84]
If there is no `fallback_module`, the `mycroft-speech.service` fails to load.

I believe it has something to do with this:
https://github.com/OpenVoiceOS/ovos-core/blob/883bdacb07b05da03377277c6a027e64c829a176/mycroft/client/speech/listener.py#L357-L359

If it was changed to this:
```
    359  -   self.fallback_stt = clazz()
    359  +  if clazz:
    360  +      self.fallback_stt = clazz()
```
I think it may work

**Comment by JarbasAl** [comment]
i believe this one has also been fixed, can you confirm @builderjer ?

**Comment by builderjer** [comment]
Yes, I have had no more issues here
